config/routes.rb
Rails.application.routes.draw do
  resources :printers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login', to: 'application#login'

  get '/organizations', to: 'organizations#index'
  post '/organizations', to: 'organizations#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
  # default_scope { where(active: true) }
  scope :active, -> { where(active: true) }

  has_many :printers
end

app/models/printer.rb
class Printer < ApplicationRecord
    # validates :name, presence: true
    validates_presence_of :name, :printer_type
    validates :description, presence: true, length: { minimum: 10 }

    validate :validate_printer_type

    belongs_to :organization

    def validate_printer_type
        errors.add(:printer_type, "is not a valid type. Choose: Tatooine or Crait") unless ['Tatooine', 'Crait'].include?(printer_type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session

    before_action :authorize_user, expect: :login

    rescue_from Unauthorized, with: :handle_user_unauthorized
 
    def handle_user_unauthorized
        # render status: :unauthorized

        respond_to do |format|
            format.html { redirect_to login_path }
            format.json { render status: :unauthorized, body: '' }
        end
    end

    def login
    end

    def authorize_user
        token = request.headers['token'] 
        raise Unauthorized if token.blank?
        raise Unauthorized if find_used_from_api(token).blank?
    end

    def find_used_from_api(token)
        # get the info from a third party api/service
        # return { name: 'Chaves', id: '100' }
        return nil
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.active
    respond_to do |format|
      format.html
      format.json { render json: @organizations }
    end

    # render json: @organizations
  end
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: %i[ show edit update destroy ]
  before_action :set_organizations, only: [:new, :edit, :create, :update]

  # GET /printers or /printers.json
  def index
    if params[:org_id].present?
      @printers = Printer.where(organization_id: params[:org_id])
    else
      @printers = Printer.all
    end
  end

  # GET /printers/1 or /printers/1.json
  def show
  end

  # GET /printers/new
  def new
    @printer = Printer.new
  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers or /printers.json
  def create
    @printer = Printer.new(printer_params)

    respond_to do |format|
      if @printer.save
        format.html { redirect_to @printer, notice: "Printer was successfully created." }
        format.json { render :show, status: :created, location: @printer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printers/1 or /printers/1.json
  def update
    respond_to do |format|
      if @printer.update(printer_params)
        format.html { redirect_to @printer, notice: "Printer was successfully updated." }
        format.json { render :show, status: :ok, location: @printer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1 or /printers/1.json
  def destroy
    @printer.destroy
    respond_to do |format|
      format.html { redirect_to printers_url, notice: "Printer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    def set_organizations
      @organizations = Organization.active
    end

    # Only allow a list of trusted parameters through.
    def printer_params
      params.require(:printer).permit(:name, :description, :organization_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrinterApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizations/index.html.erb
<h2>Organizations List</h2>

<% @organizations.each do |org| %>
    <%= org.name %> - <%= org.description %> 
    <br/>
<% end %>

app/views/printers/_form.html.erb
<%= form_with(model: printer, local: true) do |form| %>
  <% if printer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(printer.errors.count, "error") %> prohibited this printer from being saved:</h2>

      <ul>
      <% printer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :organization %>
    <%= form.collection_select(:organization_id, @organizations, :id, :name, prompt: true) %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/printers/edit.html.erb
<h1>Editing Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Show', @printer %> |
<%= link_to 'Back', printers_path %>

app/views/printers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Printers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @printers.each do |printer| %>
      <tr>
        <td><%= printer.name %></td>
        <td><%= printer.description %></td>
        <td><%= link_to 'Show', printer %></td>
        <td><%= link_to 'Edit', edit_printer_path(printer) %></td>
        <td><%= link_to 'Destroy', printer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Printer', new_printer_path %>

app/views/printers/new.html.erb
<h1>New Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Back', printers_path %>

app/views/printers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @printer.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @printer.description %>
</p>

<%= link_to 'Edit', edit_printer_path(@printer) %> |
<%= link_to 'Back', printers_path %>